import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Component navigation is the folder structure; Editor is a guide with section jumps.
const sidebars: SidebarsConfig = {
  docs: [
    "getting-started",
    "release-1-support",
    {
      type: "category",
      label: "Foundations",
      items: [
        "architecture",
        "conventions",
        "tokens",
        "overlay-contract",
        "adapter-parity",
        "docs-api-sync",
        "component-library-audit"
      ]
    }
  ],
  components: ["components", { type: "autogenerated", dirName: "components" }],
  editor: [
    "editor",
    { type: "link", label: "Try the editor", href: "/looma/editor/#try-the-editor" },
    { type: "link", label: "Add it to Vue", href: "/looma/editor/#add-it-to-a-vue-app" },
    { type: "link", label: "Formatting", href: "/looma/editor/#formatting-and-toolbar" },
    { type: "link", label: "Slash commands", href: "/looma/editor/#slash-commands-and-blocks" },
    { type: "link", label: "Code blocks", href: "/looma/editor/#code-blocks" },
    { type: "link", label: "Pasting", href: "/looma/editor/#pasting-documents" },
    { type: "link", label: "Mentions", href: "/looma/editor/#mentions" },
    { type: "link", label: "Tables", href: "/looma/editor/#tables" },
    { type: "link", label: "Images and links", href: "/looma/editor/#images-and-links" },
    { type: "link", label: "Configuration", href: "/looma/editor/#configuration-and-events" }
  ]
};

export default sidebars;
