import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Component navigation is the folder structure: docs/components/<group>/ (with _category_.json) and docs/editor/.
const sidebars: SidebarsConfig = {
  docs: [
    "getting-started",
    "release-1-support",
    {
      type: "category",
      label: "Foundations",
      items: [
        "architecture",
        "conventions",
        "tokens",
        "overlay-contract",
        "adapter-parity",
        "docs-api-sync",
        "component-library-audit"
      ]
    }
  ],
  components: ["components", { type: "autogenerated", dirName: "components" }],
  editor: ["editor", { type: "autogenerated", dirName: "editor" }]
};

export default sidebars;
