/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiAffordanceScope {
        /**
          * Distance outside each registered affordance that reveals its near state.
          * @default DEFAULT_AFFORDANCE_NEAR_RADIUS
         */
        "nearRadius": number;
    }
    interface UiAvatar {
        /**
          * @default ''
         */
        "alt": string;
        /**
          * @default ''
         */
        "fallback": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "src": string;
    }
    interface UiAvatarGroup {
        /**
          * @default 'People'
         */
        "label": string;
        /**
          * @default 5
         */
        "max": number;
    }
    interface UiBadge {
        "tone"?: string;
        "variant"?: string;
    }
    interface UiButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "size"?: string;
        /**
          * @default 'outline'
         */
        "variant": 'outline' | 'solid' | 'destructive' | 'ghost';
    }
    interface UiCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "defaultChecked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "indeterminate": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'on'
         */
        "value": string;
    }
    interface UiContextMenu {
        /**
          * Opens the menu on first client render.
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * Optional id of the region that should also respond to a context-menu gesture.
         */
        "for"?: string;
        /**
          * Controls the menu when the consumer owns open state.
          * @default false
         */
        "open": boolean;
    }
    interface UiDialog {
        /**
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * @default true
         */
        "dismissible": boolean;
        /**
          * Accessible name forwarded to the native dialog surface.
         */
        "label"?: string;
        /**
          * @default true
         */
        "modal": boolean;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface UiDisclosure {
        /**
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface UiFloatingActionButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "mobileOnly": boolean;
    }
    interface UiFormField {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default false
         */
        "required": boolean;
    }
    interface UiIconButton {
        /**
          * Reveals this control through a surrounding ui-affordance-scope.
          * @default false
         */
        "anticipatory": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'ghost'
         */
        "variant": 'ghost' | 'outline' | 'solid';
    }
    interface UiInput {
        /**
          * @default ''
         */
        "defaultValue": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default false
         */
        "readOnly": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiMenu {
        /**
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface UiMenuItem {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiPopover {
        /**
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface UiRadio {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "defaultChecked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'on'
         */
        "value": string;
    }
    interface UiRadioGroup {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiSearchResultRow {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "selected": boolean;
    }
    interface UiSearchShell {
    }
    interface UiSelect {
        /**
          * @default ''
         */
        "defaultValue": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiSwitch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "defaultChecked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'on'
         */
        "value": string;
    }
    interface UiTabs {
        /**
          * @default ''
         */
        "defaultValue": string;
        /**
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiTextarea {
        /**
          * @default ''
         */
        "defaultValue": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default false
         */
        "readOnly": boolean;
        /**
          * @default 4
         */
        "rows": number;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiToastRegion {
        /**
          * @default true
         */
        "open": boolean;
    }
    interface UiTooltip {
        /**
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * @default ''
         */
        "for": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface UiTopBar {
    }
}
declare global {
    interface HTMLUiAffordanceScopeElement extends Components.UiAffordanceScope, HTMLStencilElement {
    }
    var HTMLUiAffordanceScopeElement: {
        prototype: HTMLUiAffordanceScopeElement;
        new (): HTMLUiAffordanceScopeElement;
    };
    interface HTMLUiAvatarElement extends Components.UiAvatar, HTMLStencilElement {
    }
    var HTMLUiAvatarElement: {
        prototype: HTMLUiAvatarElement;
        new (): HTMLUiAvatarElement;
    };
    interface HTMLUiAvatarGroupElement extends Components.UiAvatarGroup, HTMLStencilElement {
    }
    var HTMLUiAvatarGroupElement: {
        prototype: HTMLUiAvatarGroupElement;
        new (): HTMLUiAvatarGroupElement;
    };
    interface HTMLUiBadgeElement extends Components.UiBadge, HTMLStencilElement {
    }
    var HTMLUiBadgeElement: {
        prototype: HTMLUiBadgeElement;
        new (): HTMLUiBadgeElement;
    };
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiCheckboxElement extends Components.UiCheckbox, HTMLStencilElement {
    }
    var HTMLUiCheckboxElement: {
        prototype: HTMLUiCheckboxElement;
        new (): HTMLUiCheckboxElement;
    };
    interface HTMLUiContextMenuElement extends Components.UiContextMenu, HTMLStencilElement {
    }
    var HTMLUiContextMenuElement: {
        prototype: HTMLUiContextMenuElement;
        new (): HTMLUiContextMenuElement;
    };
    interface HTMLUiDialogElement extends Components.UiDialog, HTMLStencilElement {
    }
    var HTMLUiDialogElement: {
        prototype: HTMLUiDialogElement;
        new (): HTMLUiDialogElement;
    };
    interface HTMLUiDisclosureElement extends Components.UiDisclosure, HTMLStencilElement {
    }
    var HTMLUiDisclosureElement: {
        prototype: HTMLUiDisclosureElement;
        new (): HTMLUiDisclosureElement;
    };
    interface HTMLUiFloatingActionButtonElement extends Components.UiFloatingActionButton, HTMLStencilElement {
    }
    var HTMLUiFloatingActionButtonElement: {
        prototype: HTMLUiFloatingActionButtonElement;
        new (): HTMLUiFloatingActionButtonElement;
    };
    interface HTMLUiFormFieldElement extends Components.UiFormField, HTMLStencilElement {
    }
    var HTMLUiFormFieldElement: {
        prototype: HTMLUiFormFieldElement;
        new (): HTMLUiFormFieldElement;
    };
    interface HTMLUiIconButtonElement extends Components.UiIconButton, HTMLStencilElement {
    }
    var HTMLUiIconButtonElement: {
        prototype: HTMLUiIconButtonElement;
        new (): HTMLUiIconButtonElement;
    };
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLUiMenuElement extends Components.UiMenu, HTMLStencilElement {
    }
    var HTMLUiMenuElement: {
        prototype: HTMLUiMenuElement;
        new (): HTMLUiMenuElement;
    };
    interface HTMLUiMenuItemElement extends Components.UiMenuItem, HTMLStencilElement {
    }
    var HTMLUiMenuItemElement: {
        prototype: HTMLUiMenuItemElement;
        new (): HTMLUiMenuItemElement;
    };
    interface HTMLUiPopoverElement extends Components.UiPopover, HTMLStencilElement {
    }
    var HTMLUiPopoverElement: {
        prototype: HTMLUiPopoverElement;
        new (): HTMLUiPopoverElement;
    };
    interface HTMLUiRadioElement extends Components.UiRadio, HTMLStencilElement {
    }
    var HTMLUiRadioElement: {
        prototype: HTMLUiRadioElement;
        new (): HTMLUiRadioElement;
    };
    interface HTMLUiRadioGroupElement extends Components.UiRadioGroup, HTMLStencilElement {
    }
    var HTMLUiRadioGroupElement: {
        prototype: HTMLUiRadioGroupElement;
        new (): HTMLUiRadioGroupElement;
    };
    interface HTMLUiSearchResultRowElement extends Components.UiSearchResultRow, HTMLStencilElement {
    }
    var HTMLUiSearchResultRowElement: {
        prototype: HTMLUiSearchResultRowElement;
        new (): HTMLUiSearchResultRowElement;
    };
    interface HTMLUiSearchShellElement extends Components.UiSearchShell, HTMLStencilElement {
    }
    var HTMLUiSearchShellElement: {
        prototype: HTMLUiSearchShellElement;
        new (): HTMLUiSearchShellElement;
    };
    interface HTMLUiSelectElement extends Components.UiSelect, HTMLStencilElement {
    }
    var HTMLUiSelectElement: {
        prototype: HTMLUiSelectElement;
        new (): HTMLUiSelectElement;
    };
    interface HTMLUiSwitchElement extends Components.UiSwitch, HTMLStencilElement {
    }
    var HTMLUiSwitchElement: {
        prototype: HTMLUiSwitchElement;
        new (): HTMLUiSwitchElement;
    };
    interface HTMLUiTabsElement extends Components.UiTabs, HTMLStencilElement {
    }
    var HTMLUiTabsElement: {
        prototype: HTMLUiTabsElement;
        new (): HTMLUiTabsElement;
    };
    interface HTMLUiTextareaElement extends Components.UiTextarea, HTMLStencilElement {
    }
    var HTMLUiTextareaElement: {
        prototype: HTMLUiTextareaElement;
        new (): HTMLUiTextareaElement;
    };
    interface HTMLUiToastRegionElement extends Components.UiToastRegion, HTMLStencilElement {
    }
    var HTMLUiToastRegionElement: {
        prototype: HTMLUiToastRegionElement;
        new (): HTMLUiToastRegionElement;
    };
    interface HTMLUiTooltipElement extends Components.UiTooltip, HTMLStencilElement {
    }
    var HTMLUiTooltipElement: {
        prototype: HTMLUiTooltipElement;
        new (): HTMLUiTooltipElement;
    };
    interface HTMLUiTopBarElement extends Components.UiTopBar, HTMLStencilElement {
    }
    var HTMLUiTopBarElement: {
        prototype: HTMLUiTopBarElement;
        new (): HTMLUiTopBarElement;
    };
    interface HTMLElementTagNameMap {
        "ui-affordance-scope": HTMLUiAffordanceScopeElement;
        "ui-avatar": HTMLUiAvatarElement;
        "ui-avatar-group": HTMLUiAvatarGroupElement;
        "ui-badge": HTMLUiBadgeElement;
        "ui-button": HTMLUiButtonElement;
        "ui-checkbox": HTMLUiCheckboxElement;
        "ui-context-menu": HTMLUiContextMenuElement;
        "ui-dialog": HTMLUiDialogElement;
        "ui-disclosure": HTMLUiDisclosureElement;
        "ui-floating-action-button": HTMLUiFloatingActionButtonElement;
        "ui-form-field": HTMLUiFormFieldElement;
        "ui-icon-button": HTMLUiIconButtonElement;
        "ui-input": HTMLUiInputElement;
        "ui-menu": HTMLUiMenuElement;
        "ui-menu-item": HTMLUiMenuItemElement;
        "ui-popover": HTMLUiPopoverElement;
        "ui-radio": HTMLUiRadioElement;
        "ui-radio-group": HTMLUiRadioGroupElement;
        "ui-search-result-row": HTMLUiSearchResultRowElement;
        "ui-search-shell": HTMLUiSearchShellElement;
        "ui-select": HTMLUiSelectElement;
        "ui-switch": HTMLUiSwitchElement;
        "ui-tabs": HTMLUiTabsElement;
        "ui-textarea": HTMLUiTextareaElement;
        "ui-toast-region": HTMLUiToastRegionElement;
        "ui-tooltip": HTMLUiTooltipElement;
        "ui-top-bar": HTMLUiTopBarElement;
    }
}
declare namespace LocalJSX {
    interface UiAffordanceScope {
        /**
          * Distance outside each registered affordance that reveals its near state.
          * @default DEFAULT_AFFORDANCE_NEAR_RADIUS
         */
        "nearRadius"?: number;
    }
    interface UiAvatar {
        /**
          * @default ''
         */
        "alt"?: string;
        /**
          * @default ''
         */
        "fallback"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default ''
         */
        "src"?: string;
    }
    interface UiAvatarGroup {
        /**
          * @default 'People'
         */
        "label"?: string;
        /**
          * @default 5
         */
        "max"?: number;
    }
    interface UiBadge {
        "tone"?: string;
        "variant"?: string;
    }
    interface UiButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "size"?: string;
        /**
          * @default 'outline'
         */
        "variant"?: 'outline' | 'solid' | 'destructive' | 'ghost';
    }
    interface UiCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "defaultChecked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'on'
         */
        "value"?: string;
    }
    interface UiContextMenu {
        /**
          * Opens the menu on first client render.
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * Optional id of the region that should also respond to a context-menu gesture.
         */
        "for"?: string;
        /**
          * Controls the menu when the consumer owns open state.
          * @default false
         */
        "open"?: boolean;
    }
    interface UiDialog {
        /**
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * @default true
         */
        "dismissible"?: boolean;
        /**
          * Accessible name forwarded to the native dialog surface.
         */
        "label"?: string;
        /**
          * @default true
         */
        "modal"?: boolean;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface UiDisclosure {
        /**
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface UiFloatingActionButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default false
         */
        "mobileOnly"?: boolean;
    }
    interface UiFormField {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface UiIconButton {
        /**
          * Reveals this control through a surrounding ui-affordance-scope.
          * @default false
         */
        "anticipatory"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'ghost'
         */
        "variant"?: 'ghost' | 'outline' | 'solid';
    }
    interface UiInput {
        /**
          * @default ''
         */
        "defaultValue"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default false
         */
        "readOnly"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiMenu {
        /**
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface UiMenuItem {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiPopover {
        /**
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface UiRadio {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "defaultChecked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'on'
         */
        "value"?: string;
    }
    interface UiRadioGroup {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiSearchResultRow {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "selected"?: boolean;
    }
    interface UiSearchShell {
    }
    interface UiSelect {
        /**
          * @default ''
         */
        "defaultValue"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiSwitch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "defaultChecked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'on'
         */
        "value"?: string;
    }
    interface UiTabs {
        /**
          * @default ''
         */
        "defaultValue"?: string;
        /**
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiTextarea {
        /**
          * @default ''
         */
        "defaultValue"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default false
         */
        "readOnly"?: boolean;
        /**
          * @default 4
         */
        "rows"?: number;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiToastRegion {
        /**
          * @default true
         */
        "open"?: boolean;
    }
    interface UiTooltip {
        /**
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * @default ''
         */
        "for"?: string;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface UiTopBar {
    }

    interface UiAffordanceScopeAttributes {
        "nearRadius": number;
    }
    interface UiAvatarAttributes {
        "src": string;
        "alt": string;
        "name": string;
        "fallback": string;
    }
    interface UiAvatarGroupAttributes {
        "max": number;
        "label": string;
    }
    interface UiBadgeAttributes {
        "variant": string;
        "tone": string;
    }
    interface UiButtonAttributes {
        "variant": 'outline' | 'solid' | 'destructive' | 'ghost';
        "size": string;
        "disabled": boolean;
    }
    interface UiCheckboxAttributes {
        "checked": boolean;
        "defaultChecked": boolean;
        "disabled": boolean;
        "indeterminate": boolean;
        "required": boolean;
        "value": string;
    }
    interface UiContextMenuAttributes {
        "open": boolean;
        "defaultOpen": boolean;
        "for": string;
    }
    interface UiDialogAttributes {
        "open": boolean;
        "defaultOpen": boolean;
        "modal": boolean;
        "dismissible": boolean;
        "label": string;
    }
    interface UiDisclosureAttributes {
        "open": boolean;
        "defaultOpen": boolean;
        "disabled": boolean;
    }
    interface UiFloatingActionButtonAttributes {
        "disabled": boolean;
        "mobileOnly": boolean;
        "label": string;
    }
    interface UiFormFieldAttributes {
        "invalid": boolean;
        "disabled": boolean;
        "required": boolean;
    }
    interface UiIconButtonAttributes {
        "disabled": boolean;
        "label": string;
        "size": 'sm' | 'md' | 'lg';
        "variant": 'ghost' | 'outline' | 'solid';
        "anticipatory": boolean;
    }
    interface UiInputAttributes {
        "value": string;
        "defaultValue": string;
        "disabled": boolean;
        "invalid": boolean;
        "readOnly": boolean;
    }
    interface UiMenuAttributes {
        "open": boolean;
        "defaultOpen": boolean;
    }
    interface UiMenuItemAttributes {
        "disabled": boolean;
        "value": string;
    }
    interface UiPopoverAttributes {
        "open": boolean;
        "defaultOpen": boolean;
    }
    interface UiRadioAttributes {
        "checked": boolean;
        "defaultChecked": boolean;
        "disabled": boolean;
        "name": string;
        "required": boolean;
        "value": string;
    }
    interface UiRadioGroupAttributes {
        "value": string;
        "name": string;
        "orientation": 'horizontal' | 'vertical';
        "disabled": boolean;
        "required": boolean;
    }
    interface UiSearchResultRowAttributes {
        "disabled": boolean;
        "selected": boolean;
    }
    interface UiSelectAttributes {
        "value": string;
        "defaultValue": string;
        "disabled": boolean;
        "invalid": boolean;
        "required": boolean;
    }
    interface UiSwitchAttributes {
        "checked": boolean;
        "defaultChecked": boolean;
        "disabled": boolean;
        "required": boolean;
        "value": string;
    }
    interface UiTabsAttributes {
        "value": string;
        "defaultValue": string;
        "orientation": 'horizontal' | 'vertical';
    }
    interface UiTextareaAttributes {
        "value": string;
        "defaultValue": string;
        "disabled": boolean;
        "invalid": boolean;
        "readOnly": boolean;
        "rows": number;
    }
    interface UiToastRegionAttributes {
        "open": boolean;
    }
    interface UiTooltipAttributes {
        "for": string;
        "open": boolean;
        "defaultOpen": boolean;
    }

    interface IntrinsicElements {
        "ui-affordance-scope": Omit<UiAffordanceScope, keyof UiAffordanceScopeAttributes> & { [K in keyof UiAffordanceScope & keyof UiAffordanceScopeAttributes]?: UiAffordanceScope[K] } & { [K in keyof UiAffordanceScope & keyof UiAffordanceScopeAttributes as `attr:${K}`]?: UiAffordanceScopeAttributes[K] } & { [K in keyof UiAffordanceScope & keyof UiAffordanceScopeAttributes as `prop:${K}`]?: UiAffordanceScope[K] };
        "ui-avatar": Omit<UiAvatar, keyof UiAvatarAttributes> & { [K in keyof UiAvatar & keyof UiAvatarAttributes]?: UiAvatar[K] } & { [K in keyof UiAvatar & keyof UiAvatarAttributes as `attr:${K}`]?: UiAvatarAttributes[K] } & { [K in keyof UiAvatar & keyof UiAvatarAttributes as `prop:${K}`]?: UiAvatar[K] };
        "ui-avatar-group": Omit<UiAvatarGroup, keyof UiAvatarGroupAttributes> & { [K in keyof UiAvatarGroup & keyof UiAvatarGroupAttributes]?: UiAvatarGroup[K] } & { [K in keyof UiAvatarGroup & keyof UiAvatarGroupAttributes as `attr:${K}`]?: UiAvatarGroupAttributes[K] } & { [K in keyof UiAvatarGroup & keyof UiAvatarGroupAttributes as `prop:${K}`]?: UiAvatarGroup[K] };
        "ui-badge": Omit<UiBadge, keyof UiBadgeAttributes> & { [K in keyof UiBadge & keyof UiBadgeAttributes]?: UiBadge[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `attr:${K}`]?: UiBadgeAttributes[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `prop:${K}`]?: UiBadge[K] };
        "ui-button": Omit<UiButton, keyof UiButtonAttributes> & { [K in keyof UiButton & keyof UiButtonAttributes]?: UiButton[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `attr:${K}`]?: UiButtonAttributes[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `prop:${K}`]?: UiButton[K] };
        "ui-checkbox": Omit<UiCheckbox, keyof UiCheckboxAttributes> & { [K in keyof UiCheckbox & keyof UiCheckboxAttributes]?: UiCheckbox[K] } & { [K in keyof UiCheckbox & keyof UiCheckboxAttributes as `attr:${K}`]?: UiCheckboxAttributes[K] } & { [K in keyof UiCheckbox & keyof UiCheckboxAttributes as `prop:${K}`]?: UiCheckbox[K] };
        "ui-context-menu": Omit<UiContextMenu, keyof UiContextMenuAttributes> & { [K in keyof UiContextMenu & keyof UiContextMenuAttributes]?: UiContextMenu[K] } & { [K in keyof UiContextMenu & keyof UiContextMenuAttributes as `attr:${K}`]?: UiContextMenuAttributes[K] } & { [K in keyof UiContextMenu & keyof UiContextMenuAttributes as `prop:${K}`]?: UiContextMenu[K] };
        "ui-dialog": Omit<UiDialog, keyof UiDialogAttributes> & { [K in keyof UiDialog & keyof UiDialogAttributes]?: UiDialog[K] } & { [K in keyof UiDialog & keyof UiDialogAttributes as `attr:${K}`]?: UiDialogAttributes[K] } & { [K in keyof UiDialog & keyof UiDialogAttributes as `prop:${K}`]?: UiDialog[K] };
        "ui-disclosure": Omit<UiDisclosure, keyof UiDisclosureAttributes> & { [K in keyof UiDisclosure & keyof UiDisclosureAttributes]?: UiDisclosure[K] } & { [K in keyof UiDisclosure & keyof UiDisclosureAttributes as `attr:${K}`]?: UiDisclosureAttributes[K] } & { [K in keyof UiDisclosure & keyof UiDisclosureAttributes as `prop:${K}`]?: UiDisclosure[K] };
        "ui-floating-action-button": Omit<UiFloatingActionButton, keyof UiFloatingActionButtonAttributes> & { [K in keyof UiFloatingActionButton & keyof UiFloatingActionButtonAttributes]?: UiFloatingActionButton[K] } & { [K in keyof UiFloatingActionButton & keyof UiFloatingActionButtonAttributes as `attr:${K}`]?: UiFloatingActionButtonAttributes[K] } & { [K in keyof UiFloatingActionButton & keyof UiFloatingActionButtonAttributes as `prop:${K}`]?: UiFloatingActionButton[K] };
        "ui-form-field": Omit<UiFormField, keyof UiFormFieldAttributes> & { [K in keyof UiFormField & keyof UiFormFieldAttributes]?: UiFormField[K] } & { [K in keyof UiFormField & keyof UiFormFieldAttributes as `attr:${K}`]?: UiFormFieldAttributes[K] } & { [K in keyof UiFormField & keyof UiFormFieldAttributes as `prop:${K}`]?: UiFormField[K] };
        "ui-icon-button": Omit<UiIconButton, keyof UiIconButtonAttributes> & { [K in keyof UiIconButton & keyof UiIconButtonAttributes]?: UiIconButton[K] } & { [K in keyof UiIconButton & keyof UiIconButtonAttributes as `attr:${K}`]?: UiIconButtonAttributes[K] } & { [K in keyof UiIconButton & keyof UiIconButtonAttributes as `prop:${K}`]?: UiIconButton[K] };
        "ui-input": Omit<UiInput, keyof UiInputAttributes> & { [K in keyof UiInput & keyof UiInputAttributes]?: UiInput[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `attr:${K}`]?: UiInputAttributes[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `prop:${K}`]?: UiInput[K] };
        "ui-menu": Omit<UiMenu, keyof UiMenuAttributes> & { [K in keyof UiMenu & keyof UiMenuAttributes]?: UiMenu[K] } & { [K in keyof UiMenu & keyof UiMenuAttributes as `attr:${K}`]?: UiMenuAttributes[K] } & { [K in keyof UiMenu & keyof UiMenuAttributes as `prop:${K}`]?: UiMenu[K] };
        "ui-menu-item": Omit<UiMenuItem, keyof UiMenuItemAttributes> & { [K in keyof UiMenuItem & keyof UiMenuItemAttributes]?: UiMenuItem[K] } & { [K in keyof UiMenuItem & keyof UiMenuItemAttributes as `attr:${K}`]?: UiMenuItemAttributes[K] } & { [K in keyof UiMenuItem & keyof UiMenuItemAttributes as `prop:${K}`]?: UiMenuItem[K] };
        "ui-popover": Omit<UiPopover, keyof UiPopoverAttributes> & { [K in keyof UiPopover & keyof UiPopoverAttributes]?: UiPopover[K] } & { [K in keyof UiPopover & keyof UiPopoverAttributes as `attr:${K}`]?: UiPopoverAttributes[K] } & { [K in keyof UiPopover & keyof UiPopoverAttributes as `prop:${K}`]?: UiPopover[K] };
        "ui-radio": Omit<UiRadio, keyof UiRadioAttributes> & { [K in keyof UiRadio & keyof UiRadioAttributes]?: UiRadio[K] } & { [K in keyof UiRadio & keyof UiRadioAttributes as `attr:${K}`]?: UiRadioAttributes[K] } & { [K in keyof UiRadio & keyof UiRadioAttributes as `prop:${K}`]?: UiRadio[K] };
        "ui-radio-group": Omit<UiRadioGroup, keyof UiRadioGroupAttributes> & { [K in keyof UiRadioGroup & keyof UiRadioGroupAttributes]?: UiRadioGroup[K] } & { [K in keyof UiRadioGroup & keyof UiRadioGroupAttributes as `attr:${K}`]?: UiRadioGroupAttributes[K] } & { [K in keyof UiRadioGroup & keyof UiRadioGroupAttributes as `prop:${K}`]?: UiRadioGroup[K] };
        "ui-search-result-row": Omit<UiSearchResultRow, keyof UiSearchResultRowAttributes> & { [K in keyof UiSearchResultRow & keyof UiSearchResultRowAttributes]?: UiSearchResultRow[K] } & { [K in keyof UiSearchResultRow & keyof UiSearchResultRowAttributes as `attr:${K}`]?: UiSearchResultRowAttributes[K] } & { [K in keyof UiSearchResultRow & keyof UiSearchResultRowAttributes as `prop:${K}`]?: UiSearchResultRow[K] };
        "ui-search-shell": UiSearchShell;
        "ui-select": Omit<UiSelect, keyof UiSelectAttributes> & { [K in keyof UiSelect & keyof UiSelectAttributes]?: UiSelect[K] } & { [K in keyof UiSelect & keyof UiSelectAttributes as `attr:${K}`]?: UiSelectAttributes[K] } & { [K in keyof UiSelect & keyof UiSelectAttributes as `prop:${K}`]?: UiSelect[K] };
        "ui-switch": Omit<UiSwitch, keyof UiSwitchAttributes> & { [K in keyof UiSwitch & keyof UiSwitchAttributes]?: UiSwitch[K] } & { [K in keyof UiSwitch & keyof UiSwitchAttributes as `attr:${K}`]?: UiSwitchAttributes[K] } & { [K in keyof UiSwitch & keyof UiSwitchAttributes as `prop:${K}`]?: UiSwitch[K] };
        "ui-tabs": Omit<UiTabs, keyof UiTabsAttributes> & { [K in keyof UiTabs & keyof UiTabsAttributes]?: UiTabs[K] } & { [K in keyof UiTabs & keyof UiTabsAttributes as `attr:${K}`]?: UiTabsAttributes[K] } & { [K in keyof UiTabs & keyof UiTabsAttributes as `prop:${K}`]?: UiTabs[K] };
        "ui-textarea": Omit<UiTextarea, keyof UiTextareaAttributes> & { [K in keyof UiTextarea & keyof UiTextareaAttributes]?: UiTextarea[K] } & { [K in keyof UiTextarea & keyof UiTextareaAttributes as `attr:${K}`]?: UiTextareaAttributes[K] } & { [K in keyof UiTextarea & keyof UiTextareaAttributes as `prop:${K}`]?: UiTextarea[K] };
        "ui-toast-region": Omit<UiToastRegion, keyof UiToastRegionAttributes> & { [K in keyof UiToastRegion & keyof UiToastRegionAttributes]?: UiToastRegion[K] } & { [K in keyof UiToastRegion & keyof UiToastRegionAttributes as `attr:${K}`]?: UiToastRegionAttributes[K] } & { [K in keyof UiToastRegion & keyof UiToastRegionAttributes as `prop:${K}`]?: UiToastRegion[K] };
        "ui-tooltip": Omit<UiTooltip, keyof UiTooltipAttributes> & { [K in keyof UiTooltip & keyof UiTooltipAttributes]?: UiTooltip[K] } & { [K in keyof UiTooltip & keyof UiTooltipAttributes as `attr:${K}`]?: UiTooltipAttributes[K] } & { [K in keyof UiTooltip & keyof UiTooltipAttributes as `prop:${K}`]?: UiTooltip[K] };
        "ui-top-bar": UiTopBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-affordance-scope": LocalJSX.IntrinsicElements["ui-affordance-scope"] & JSXBase.HTMLAttributes<HTMLUiAffordanceScopeElement>;
            "ui-avatar": LocalJSX.IntrinsicElements["ui-avatar"] & JSXBase.HTMLAttributes<HTMLUiAvatarElement>;
            "ui-avatar-group": LocalJSX.IntrinsicElements["ui-avatar-group"] & JSXBase.HTMLAttributes<HTMLUiAvatarGroupElement>;
            "ui-badge": LocalJSX.IntrinsicElements["ui-badge"] & JSXBase.HTMLAttributes<HTMLUiBadgeElement>;
            "ui-button": LocalJSX.IntrinsicElements["ui-button"] & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-checkbox": LocalJSX.IntrinsicElements["ui-checkbox"] & JSXBase.HTMLAttributes<HTMLUiCheckboxElement>;
            "ui-context-menu": LocalJSX.IntrinsicElements["ui-context-menu"] & JSXBase.HTMLAttributes<HTMLUiContextMenuElement>;
            "ui-dialog": LocalJSX.IntrinsicElements["ui-dialog"] & JSXBase.HTMLAttributes<HTMLUiDialogElement>;
            "ui-disclosure": LocalJSX.IntrinsicElements["ui-disclosure"] & JSXBase.HTMLAttributes<HTMLUiDisclosureElement>;
            "ui-floating-action-button": LocalJSX.IntrinsicElements["ui-floating-action-button"] & JSXBase.HTMLAttributes<HTMLUiFloatingActionButtonElement>;
            "ui-form-field": LocalJSX.IntrinsicElements["ui-form-field"] & JSXBase.HTMLAttributes<HTMLUiFormFieldElement>;
            "ui-icon-button": LocalJSX.IntrinsicElements["ui-icon-button"] & JSXBase.HTMLAttributes<HTMLUiIconButtonElement>;
            "ui-input": LocalJSX.IntrinsicElements["ui-input"] & JSXBase.HTMLAttributes<HTMLUiInputElement>;
            "ui-menu": LocalJSX.IntrinsicElements["ui-menu"] & JSXBase.HTMLAttributes<HTMLUiMenuElement>;
            "ui-menu-item": LocalJSX.IntrinsicElements["ui-menu-item"] & JSXBase.HTMLAttributes<HTMLUiMenuItemElement>;
            "ui-popover": LocalJSX.IntrinsicElements["ui-popover"] & JSXBase.HTMLAttributes<HTMLUiPopoverElement>;
            "ui-radio": LocalJSX.IntrinsicElements["ui-radio"] & JSXBase.HTMLAttributes<HTMLUiRadioElement>;
            "ui-radio-group": LocalJSX.IntrinsicElements["ui-radio-group"] & JSXBase.HTMLAttributes<HTMLUiRadioGroupElement>;
            "ui-search-result-row": LocalJSX.IntrinsicElements["ui-search-result-row"] & JSXBase.HTMLAttributes<HTMLUiSearchResultRowElement>;
            "ui-search-shell": LocalJSX.IntrinsicElements["ui-search-shell"] & JSXBase.HTMLAttributes<HTMLUiSearchShellElement>;
            "ui-select": LocalJSX.IntrinsicElements["ui-select"] & JSXBase.HTMLAttributes<HTMLUiSelectElement>;
            "ui-switch": LocalJSX.IntrinsicElements["ui-switch"] & JSXBase.HTMLAttributes<HTMLUiSwitchElement>;
            "ui-tabs": LocalJSX.IntrinsicElements["ui-tabs"] & JSXBase.HTMLAttributes<HTMLUiTabsElement>;
            "ui-textarea": LocalJSX.IntrinsicElements["ui-textarea"] & JSXBase.HTMLAttributes<HTMLUiTextareaElement>;
            "ui-toast-region": LocalJSX.IntrinsicElements["ui-toast-region"] & JSXBase.HTMLAttributes<HTMLUiToastRegionElement>;
            "ui-tooltip": LocalJSX.IntrinsicElements["ui-tooltip"] & JSXBase.HTMLAttributes<HTMLUiTooltipElement>;
            "ui-top-bar": LocalJSX.IntrinsicElements["ui-top-bar"] & JSXBase.HTMLAttributes<HTMLUiTopBarElement>;
        }
    }
}
