// This file is generated by tools/scripts/generate-vue-component-types.mjs. Do not edit manually.
import type { VueAdapterEventMap } from './adapter';

export interface AdapterBaseProps {
  'data-allow-mismatch'?: string;
}

export interface StackProps extends AdapterBaseProps {
  "align"?: "start" | "center" | "end" | "stretch" | undefined;
  "gap"?: "xs" | "s" | "m" | "l" | "xl" | undefined;
  "justify"?: "start" | "center" | "end" | "between" | undefined;
}

export interface ClusterProps extends AdapterBaseProps {
  "align"?: "start" | "center" | "end" | "stretch" | undefined;
  "gap"?: "xs" | "s" | "m" | "l" | "xl" | undefined;
}

export interface GridProps extends AdapterBaseProps {
  "gap"?: "xs" | "s" | "m" | "l" | "xl" | undefined;
  "min"?: "sm" | "md" | "lg" | undefined;
}

export interface ContainerProps extends AdapterBaseProps {
  "gutters"?: "s" | "m" | "l" | undefined;
  "measure"?: "narrow" | "wide" | undefined;
}

export interface SwitcherProps extends AdapterBaseProps {
  "align"?: "start" | "center" | "end" | "stretch" | undefined;
  "gap"?: "xs" | "s" | "m" | "l" | "xl" | undefined;
  "threshold"?: "xs" | "sm" | "md" | "lg" | undefined;
}

export interface SidebarProps extends AdapterBaseProps {
  "breakpoint"?: "sm" | "md" | "lg" | undefined;
  "collapsed"?: boolean | undefined;
  "maxWidth"?: number | undefined;
  "minWidth"?: number | undefined;
  "resizable"?: boolean | undefined;
  "resizeLabel"?: string | undefined;
  "resizeStep"?: number | undefined;
  "side"?: "start" | "end" | undefined;
  "width"?: number | undefined;
}

export interface ReelProps extends AdapterBaseProps {
  "gap"?: "xs" | "s" | "m" | "l" | "xl" | undefined;
  "itemWidth"?: "sm" | "md" | "lg" | undefined;
  "snap"?: "start" | "center" | undefined;
}

export interface SeparatorProps extends AdapterBaseProps {
  "orientation"?: "horizontal" | "vertical" | undefined;
}

export interface DisclosureProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "open"?: boolean | undefined;
  "summary"?: string | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface EditableProps extends AdapterBaseProps {
  "actions"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "edit"?: boolean | undefined;
  "hint"?: string | undefined;
  "label"?: string | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
  "onEditChange"?: ((detail: VueAdapterEventMap['editChange']) => void) | undefined;
  "onInput"?: ((detail: VueAdapterEventMap['input']) => void) | undefined;
}

export interface TabsProps extends AdapterBaseProps {
  "label"?: string | undefined;
  "orientation"?: "horizontal" | "vertical" | undefined;
  "stretch"?: boolean | undefined;
  "value"?: string | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface DialogProps extends AdapterBaseProps {
  "dismissible"?: boolean | undefined;
  "for"?: string | undefined;
  "label"?: string | undefined;
  "modal"?: boolean | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
}

export interface PopoverProps extends AdapterBaseProps {
  "for"?: string | undefined;
  "open"?: boolean | undefined;
  "placement"?: string | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface MenuProps extends AdapterBaseProps {
  "for"?: string | undefined;
  "open"?: boolean | undefined;
  "placement"?: string | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface MenuItemProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "value"?: string | undefined;
}

export interface ContextMenuProps extends AdapterBaseProps {
  "for"?: string | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface AffordanceScopeProps extends AdapterBaseProps {
  "nearRadius"?: number | undefined;
}

export interface ButtonProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "size"?: "sm" | "md" | "lg" | undefined;
  "variant"?: "outline" | "solid" | "danger" | "ghost" | "link" | undefined;
}

export interface IconButtonProps extends AdapterBaseProps {
  "anticipatory"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "label"?: string | undefined;
  "round"?: boolean | undefined;
  "size"?: "sm" | "md" | "lg" | undefined;
  "variant"?: "ghost" | "outline" | "solid" | undefined;
}

export interface InputProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "readonly"?: boolean | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "modelValue"?: string | undefined;
  "onUpdate:modelValue"?: ((value: string) => void) | undefined;
  "onInput"?: ((event: Event) => void) | undefined;
  "onChange"?: ((event: Event) => void) | undefined;
}

export interface SelectProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "multiple"?: boolean | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "modelValue"?: string | undefined;
  "onUpdate:modelValue"?: ((value: string) => void) | undefined;
  "onInput"?: ((event: Event) => void) | undefined;
  "onChange"?: ((event: Event) => void) | undefined;
}

export interface TextareaProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "readonly"?: boolean | undefined;
  "required"?: boolean | undefined;
  "rows"?: number | undefined;
  "value"?: string | undefined;
  "modelValue"?: string | undefined;
  "onUpdate:modelValue"?: ((value: string) => void) | undefined;
  "onInput"?: ((event: Event) => void) | undefined;
  "onChange"?: ((event: Event) => void) | undefined;
}

export interface FormFieldProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "required"?: boolean | undefined;
}

export interface TooltipProps extends AdapterBaseProps {
  "for"?: string | undefined;
  "hideDelay"?: number | undefined;
  "inverse"?: boolean | undefined;
  "open"?: boolean | undefined;
  "placement"?: string | undefined;
  "showDelay"?: number | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface ToastRegionProps extends AdapterBaseProps {
  "auto"?: boolean | undefined;
  "duration"?: number | undefined;
  "message"?: string | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onDismiss"?: ((detail: VueAdapterEventMap['dismiss']) => void) | undefined;
}

export interface CheckboxProps extends AdapterBaseProps {
  "checked"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "indeterminate"?: boolean | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
}

export interface SwitchProps extends AdapterBaseProps {
  "checked"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
}

export interface RadioGroupProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "label"?: string | undefined;
  "name"?: string | undefined;
  "orientation"?: "horizontal" | "vertical" | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface RadioProps extends AdapterBaseProps {
  "checked"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "name"?: string | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
}

export interface BadgeProps extends AdapterBaseProps {
  "tone"?: "neutral" | "accent" | "info" | "success" | "warning" | "danger" | undefined;
  "variant"?: "solid" | "subtle" | undefined;
}

export interface CalloutProps extends AdapterBaseProps {
  "tone"?: "info" | "note" | "warning" | "success" | "danger" | undefined;
}

export interface AvatarProps extends AdapterBaseProps {
  "alt"?: string | undefined;
  "fallback"?: string | undefined;
  "name"?: string | undefined;
  "src"?: string | undefined;
}

export interface AvatarGroupProps extends AdapterBaseProps {
  "label"?: string | undefined;
  "max"?: number | undefined;
}

export interface SearchShellProps extends AdapterBaseProps {
  "dismissible"?: boolean | undefined;
  "label"?: string | undefined;
  "modal"?: boolean | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
}

export interface SearchResultRowProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "selected"?: boolean | undefined;
}

export interface TopBarProps extends AdapterBaseProps {
}

export interface TreeProps extends AdapterBaseProps {
  "hoverExpandDelay"?: number | undefined;
  "label"?: string | undefined;
  "maxDepth"?: number | undefined;
  "onReorder"?: ((detail: VueAdapterEventMap['reorder']) => void) | undefined;
  "onReorderRejected"?: ((detail: VueAdapterEventMap['reorderRejected']) => void) | undefined;
}

export interface TreeItemProps extends AdapterBaseProps {
  "accepts"?: string | undefined;
  "container"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "dragType"?: string | undefined;
  "dropDepth"?: number | undefined;
  "dropScope"?: string | undefined;
  "expanded"?: boolean | undefined;
  "itemId"?: string | undefined;
  "label"?: string | undefined;
  "selected"?: boolean | undefined;
  "sortable"?: boolean | undefined;
  "subtreeDepth"?: number | undefined;
  "onExpand"?: ((detail: VueAdapterEventMap['expand']) => void) | undefined;
}

export interface AdapterComponentProps {
  "Stack": StackProps;
  "Cluster": ClusterProps;
  "Grid": GridProps;
  "Container": ContainerProps;
  "Switcher": SwitcherProps;
  "Sidebar": SidebarProps;
  "Reel": ReelProps;
  "Separator": SeparatorProps;
  "Disclosure": DisclosureProps;
  "Editable": EditableProps;
  "Tabs": TabsProps;
  "Dialog": DialogProps;
  "Popover": PopoverProps;
  "Menu": MenuProps;
  "MenuItem": MenuItemProps;
  "ContextMenu": ContextMenuProps;
  "AffordanceScope": AffordanceScopeProps;
  "Button": ButtonProps;
  "IconButton": IconButtonProps;
  "Input": InputProps;
  "Select": SelectProps;
  "Textarea": TextareaProps;
  "FormField": FormFieldProps;
  "Tooltip": TooltipProps;
  "ToastRegion": ToastRegionProps;
  "Checkbox": CheckboxProps;
  "Switch": SwitchProps;
  "RadioGroup": RadioGroupProps;
  "Radio": RadioProps;
  "Badge": BadgeProps;
  "Callout": CalloutProps;
  "Avatar": AvatarProps;
  "AvatarGroup": AvatarGroupProps;
  "SearchShell": SearchShellProps;
  "SearchResultRow": SearchResultRowProps;
  "TopBar": TopBarProps;
  "Tree": TreeProps;
  "TreeItem": TreeItemProps;
}
