// This file is generated by tools/scripts/generate-vue-component-types.mjs. Do not edit manually.
import type { VueAdapterEventMap } from './adapter';

export interface AdapterBaseProps {
  'data-allow-mismatch'?: string;
}

export interface StackProps extends AdapterBaseProps {
  "align"?: string | undefined;
  "gap"?: string | undefined;
  "justify"?: string | undefined;
}

export interface InlineProps extends AdapterBaseProps {
  "align"?: string | undefined;
  "gap"?: string | undefined;
  "justify"?: string | undefined;
  "wrap"?: string | undefined;
}

export interface ClusterProps extends AdapterBaseProps {
  "align"?: string | undefined;
  "gap"?: string | undefined;
  "justify"?: string | undefined;
}

export interface GridProps extends AdapterBaseProps {
  "gap"?: string | undefined;
  "min"?: string | undefined;
}

export interface CenterProps extends AdapterBaseProps {
  "gutters"?: string | undefined;
  "measure"?: string | undefined;
}

export interface SwitcherProps extends AdapterBaseProps {
  "align"?: string | undefined;
  "gap"?: string | undefined;
  "threshold"?: string | undefined;
}

export interface SidebarProps extends AdapterBaseProps {
  "align"?: string | undefined;
  "gap"?: string | undefined;
  "side"?: string | undefined;
  "width"?: string | undefined;
  "resizable"?: boolean | undefined;
}

export interface ReelProps extends AdapterBaseProps {
  "gap"?: string | undefined;
  "itemWidth"?: string | undefined;
  "snap"?: string | undefined;
}

export interface SeparatorProps extends AdapterBaseProps {
  "orientation"?: string | undefined;
}

export interface DisclosureProps extends AdapterBaseProps {
  "defaultOpen"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface TabsProps extends AdapterBaseProps {
  "defaultValue"?: string | undefined;
  "orientation"?: "horizontal" | "vertical" | undefined;
  "value"?: string | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface DialogProps extends AdapterBaseProps {
  "defaultOpen"?: boolean | undefined;
  "dismissible"?: boolean | undefined;
  "modal"?: boolean | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface PopoverProps extends AdapterBaseProps {
  "defaultOpen"?: boolean | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface MenuProps extends AdapterBaseProps {
  "defaultOpen"?: boolean | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface MenuItemProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "value"?: string | undefined;
}

export interface ContextMenuProps extends AdapterBaseProps {
  "defaultOpen"?: boolean | undefined;
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface AffordanceScopeProps extends AdapterBaseProps {
  "nearRadius"?: number | undefined;
}

export interface ButtonProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "size"?: string | undefined;
  "variant"?: string | undefined;
}

export interface IconButtonProps extends AdapterBaseProps {
  "anticipatory"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "label"?: string | undefined;
  "size"?: "sm" | "md" | "lg" | undefined;
  "variant"?: "ghost" | "outline" | "solid" | undefined;
}

export interface InputProps extends AdapterBaseProps {
  "defaultValue"?: string | undefined;
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "readOnly"?: boolean | undefined;
  "value"?: string | undefined;
}

export interface SelectProps extends AdapterBaseProps {
  "defaultValue"?: string | undefined;
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
}

export interface TextareaProps extends AdapterBaseProps {
  "defaultValue"?: string | undefined;
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "readOnly"?: boolean | undefined;
  "rows"?: number | undefined;
  "value"?: string | undefined;
}

export interface FormFieldProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "invalid"?: boolean | undefined;
  "required"?: boolean | undefined;
}

export interface TooltipProps extends AdapterBaseProps {
  "defaultOpen"?: boolean | undefined;
  "for"?: string | undefined;
  "open"?: boolean | undefined;
  "toggleOnClick"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface ToastRegionProps extends AdapterBaseProps {
  "open"?: boolean | undefined;
  "onClose"?: ((detail: VueAdapterEventMap['close']) => void) | undefined;
  "onDismiss"?: ((detail: VueAdapterEventMap['dismiss']) => void) | undefined;
  "onOpen"?: ((detail: VueAdapterEventMap['open']) => void) | undefined;
}

export interface CheckboxProps extends AdapterBaseProps {
  "checked"?: boolean | undefined;
  "defaultChecked"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "indeterminate"?: boolean | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
}

export interface SwitchProps extends AdapterBaseProps {
  "checked"?: boolean | undefined;
  "defaultChecked"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
}

export interface RadioGroupProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "name"?: string | undefined;
  "orientation"?: "horizontal" | "vertical" | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
  "onSelect"?: ((detail: VueAdapterEventMap['select']) => void) | undefined;
}

export interface RadioProps extends AdapterBaseProps {
  "checked"?: boolean | undefined;
  "defaultChecked"?: boolean | undefined;
  "disabled"?: boolean | undefined;
  "name"?: string | undefined;
  "required"?: boolean | undefined;
  "value"?: string | undefined;
  "onChange"?: ((detail: VueAdapterEventMap['change']) => void) | undefined;
}

export interface BadgeProps extends AdapterBaseProps {
  "tone"?: string | undefined;
  "variant"?: string | undefined;
}

export interface AvatarProps extends AdapterBaseProps {
  "alt"?: string | undefined;
  "fallback"?: string | undefined;
  "name"?: string | undefined;
  "src"?: string | undefined;
}

export interface AvatarGroupProps extends AdapterBaseProps {
  "label"?: string | undefined;
  "max"?: number | undefined;
}

export interface FloatingActionButtonProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "label"?: string | undefined;
  "mobileOnly"?: boolean | undefined;
}

export interface SearchShellProps extends AdapterBaseProps {
}

export interface SearchResultRowProps extends AdapterBaseProps {
  "disabled"?: boolean | undefined;
  "selected"?: boolean | undefined;
}

export interface TopBarProps extends AdapterBaseProps {
}

export interface TreeProps extends AdapterBaseProps {
  "hoverExpandDelay"?: number | undefined;
  "label"?: string | undefined;
  "maxDepth"?: number | undefined;
  "onReorder"?: ((detail: VueAdapterEventMap['reorder']) => void) | undefined;
  "onReorderRejected"?: ((detail: VueAdapterEventMap['reorderRejected']) => void) | undefined;
}

export interface TreeItemProps extends AdapterBaseProps {
  "accepts"?: string | undefined;
  "container"?: boolean | undefined;
  "defaultExpanded"?: boolean | undefined;
  "depth"?: number | undefined;
  "disabled"?: boolean | undefined;
  "dragType"?: string | undefined;
  "dropScope"?: string | undefined;
  "expanded"?: boolean | undefined;
  "itemId"?: string | undefined;
  "label"?: string | undefined;
  "selected"?: boolean | undefined;
  "sortable"?: boolean | undefined;
  "onExpand"?: ((detail: VueAdapterEventMap['expand']) => void) | undefined;
}

export interface AdapterComponentProps {
  "Stack": StackProps;
  "Inline": InlineProps;
  "Cluster": ClusterProps;
  "Grid": GridProps;
  "Center": CenterProps;
  "Switcher": SwitcherProps;
  "Sidebar": SidebarProps;
  "Reel": ReelProps;
  "Separator": SeparatorProps;
  "Disclosure": DisclosureProps;
  "Tabs": TabsProps;
  "Dialog": DialogProps;
  "Popover": PopoverProps;
  "Menu": MenuProps;
  "MenuItem": MenuItemProps;
  "ContextMenu": ContextMenuProps;
  "AffordanceScope": AffordanceScopeProps;
  "Button": ButtonProps;
  "IconButton": IconButtonProps;
  "Input": InputProps;
  "Select": SelectProps;
  "Textarea": TextareaProps;
  "FormField": FormFieldProps;
  "Tooltip": TooltipProps;
  "ToastRegion": ToastRegionProps;
  "Checkbox": CheckboxProps;
  "Switch": SwitchProps;
  "RadioGroup": RadioGroupProps;
  "Radio": RadioProps;
  "Badge": BadgeProps;
  "Avatar": AvatarProps;
  "AvatarGroup": AvatarGroupProps;
  "FloatingActionButton": FloatingActionButtonProps;
  "SearchShell": SearchShellProps;
  "SearchResultRow": SearchResultRowProps;
  "TopBar": TopBarProps;
  "Tree": TreeProps;
  "TreeItem": TreeItemProps;
}
